# Site settings
title: System-on-Chip Design & Verification
author: 
  name: Nasir Ahmad
  email: G00419630@atu.ie
description: "System on Chip Design and Verification Project"

# Build settings
remote_theme: jekyll/minima
